# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- 'main'

pool:
  vmImage: ubuntu-latest
  demands:
  - npm

variables:
  buildConfiguration: 'Release'
  wwwrootDirectory: 'Tailspin.SpaceGame.Web/wwwroot'
  projects: '**/*.sln'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '6.x'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK $(dotnetSdkVersion)'
  inputs:
    packageType: 'sdk'
    version: '$(dotnetSdkVersion)'

- task: NuGetToolInstaller@0
  inputs:
    versionSpec: '5.9.1'

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false

- script: 'npx sass $(wwwrootDirectory) --source-map'
  displayName: 'Compile Sass'

- task: gulp@1
  displayName: 'Executa o gulp'

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info'
  workingDirectory: $(wwwrootDirectory)
  workingDirectory: $(wwwrootDir)

- task: NuGetCommand@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: '$(System.TeamProject)/Tailspin.SpaceGame.Web.Models'

- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: $(projects)

- template: templates/build.yml
  parameters:
    buildConfiguration: 'Debug'

- template: templates/build.yml
  parameters:
    buildConfiguration: 'Release'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact: drop'
  condition: succeeded()
